# Site settings
title: Zheng Ziyin
SEOTitle: 郑子吟的博客 | Zheng Ziyin Blog
header-img:  img/head_img.jpg
# header-img: img/home-bg.jpg
email: lovery_zheng@163.com
description: "成为一个有态度的产品架构师!"
# keyword: "黄玄, Hux黄玄, Hux, 鬼栈, huxpro, @huxpro, 黄玄的博客, Hux Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "https://misslovery.github.io/"              # your host, for absolute URL
# baseurl: "/about"                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     huxpro
# zhihu_username:     huxpro
github_username:    misslovery
# twitter_username:   huxpro
# facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx
google_scholar_username:  vUlkWIEAAAAJ
chatbot_http:  http://124.222.119.248:3000/



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate, jekyll-redirect-from]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: zhangjian

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: 4a3078b34174267e9a71e33bb963a583

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: misslovery.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "成为一个有态度的产品架构师！"
sidebar-avatar: /img/personal.jpg # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true


# # Friends
# friends: [
#   {}
# ]
